In [1]:
import pandas as pd

In [2]:
df= pd.read_csv('./data/train.csv')

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 126244 entries, 0 to 126243
Data columns (total 35 columns):
 #   Column              Non-Null Count   Dtype
---  ------              --------------   -----
 0   ID                  126244 non-null  object
 1   환자 시술 당시 나이         126244 non-null  object
 2   시술 유형               126244 non-null  object
 3   세부 시술 유형            126242 non-null  object
 4   배란 자극 시술 여부         126244 non-null  bool
 5   단일 배아 이식 여부         126244 non-null  bool
 6   불임 원인 - 난관 질환       126244 non-null  bool
 7   불임 원인 - 배란 장애       126244 non-null  bool
 8   불임 원인 - 남성 요인       126244 non-null  bool
 9   불임 원인 - 자궁내막증       126244 non-null  bool
 10  불임 원인 - 불명확         126244 non-null  bool
 11  이전 IVF 시술 횟수        126244 non-null  object
 12  이전 DI 시술 횟수         126244 non-null  object
 13  이전 총 임신 횟수          114541 non-null  object
 14  이전 총 임신 성공 횟수       121163 non-null  object
 15  총 생성 배아 수           125397 non-null  object
 16  이식된 배아 수            125397 non-null  float64
 17  미세주입(ICSI) 배아 이식 수  117354 non-null  float64
 18  저장된 배아 수            125397 non-null  object
 19  해동된 배아 수            126244 non-null  object
 20  해동 난자 사용 여부         126244 non-null  bool
 21  채취된 신선 난자 수         125397 non-null  object
 22  신선 난자 사용 여부         126244 non-null  bool
 23  수정 시도된 난자 수         125397 non-null  object
 24  난자 출처               126244 non-null  object
 25  정자 출처               126244 non-null  object
 26  난자 기증자 나이           126244 non-null  object
 27  정자 기증자 나이           126244 non-null  object
 28  동결 배아 사용 여부         126244 non-null  bool
 29  신선 배아 사용 여부         126244 non-null  bool
 30  기증 배아 사용 여부         126244 non-null  bool
 31  착상 전 PGD 시행 여부      126244 non-null  bool
 32  착상 전 PGS 시행 여부      126244 non-null  bool
 33  배아 이식 후 경과일         108804 non-null  float64
 34  임신 성공 확률            126244 non-null  float64
dtypes: bool(14), float64(4), object(17)
memory usage: 21.9+ MB

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 126244 entries, 0 to 126243
Data columns (total 35 columns):
 #   Column              Non-Null Count   Dtype
---  ------              --------------   -----
 0   ID                  126244 non-null  object
 1   환자 시술 당시 나이         126244 non-null  object
 2   시술 유형               126244 non-null  object
 3   세부 시술 유형            126242 non-null  object
 4   배란 자극 시술 여부         126244 non-null  bool
 5   단일 배아 이식 여부         126244 non-null  bool
 6   불임 원인 - 난관 질환       126244 non-null  bool
 7   불임 원인 - 배란 장애       126244 non-null  bool
 8   불임 원인 - 남성 요인       126244 non-null  bool
 9   불임 원인 - 자궁내막증       126244 non-null  bool
 10  불임 원인 - 불명확         126244 non-null  bool
 11  이전 IVF 시술 횟수        126244 non-null  object
 12  이전 DI 시술 횟수         126244 non-null  object
 13  이전 총 임신 횟수          114541 non-null  object
 14  이전 총 임신 성공 횟수       121163 non-null  object
 15  총 생성 배아 수           125397 non-null  object
 16  이식된 배아 수            125397 non-null  float64
 17  미세주입(ICSI) 배아 이식 수  117354 non-null  float64
 18  저장된 배아 수            125397 non-null  object
 19  해동된 배아 수            126244 non-null  object
 20  해동 난자 사용 여부         126244 non-null  bool
 21  채취된 신선 난자 수         125397 non-null  object
 22  신선 난자 사용 여부         126244 non-null  bool
 23  수정 시도된 난자 수         125397 non-null  object
 24  난자 출처               126244 non-null  object
 25  정자 출처               126244 non-null  object
 26  난자 기증자 나이           126244 non-null  object
 27  정자 기증자 나이           126244 non-null  object
 28  동결 배아 사용 여부         126244 non-null  bool
 29  신선 배아 사용 여부         126244 non-null  bool
 30  기증 배아 사용 여부         126244 non-null  bool
 31  착상 전 PGD 시행 여부      126244 non-null  bool
 32  착상 전 PGS 시행 여부      126244 non-null  bool
 33  배아 이식 후 경과일         108804 non-null  float64
 34  임신 성공 확률            126244 non-null  float64
dtypes: bool(14), float64(4), object(17)
memory usage: 21.9+ MB

In [5]:
df.isnull().sum()

ID                        0
환자 시술 당시 나이               0
시술 유형                     0
세부 시술 유형                  2
배란 자극 시술 여부               0
단일 배아 이식 여부               0
불임 원인 - 난관 질환             0
불임 원인 - 배란 장애             0
불임 원인 - 남성 요인             0
불임 원인 - 자궁내막증             0
불임 원인 - 불명확               0
이전 IVF 시술 횟수              0
이전 DI 시술 횟수               0
이전 총 임신 횟수            11703
이전 총 임신 성공 횟수          5081
총 생성 배아 수               847
이식된 배아 수                847
미세주입(ICSI) 배아 이식 수     8890
저장된 배아 수                847
해동된 배아 수                  0
해동 난자 사용 여부               0
채취된 신선 난자 수             847
신선 난자 사용 여부               0
수정 시도된 난자 수             847
난자 출처                     0
정자 출처                     0
난자 기증자 나이                 0
정자 기증자 나이                 0
동결 배아 사용 여부               0
신선 배아 사용 여부               0
기증 배아 사용 여부               0
착상 전 PGD 시행 여부            0
착상 전 PGS 시행 여부            0
배아 이식 후 경과일           17440
임신 성공 확률                  0
dtype: int64

In [6]:
columns3 = ['채취된 신선 난자 수', 
'수정 시도된 난자 수',
'해동된 배아 수', 
'저장된 배아 수', 
'총 생성 배아 수', 
'이식된 배아 수', 
'미세주입(ICSI) 배아 이식 수', 
'해동 난자 사용 여부', 
'신선 난자 사용 여부', 
'난자 출처', '정자 출처', 
'난자 기증자 나이', '정자 기증자 나이', 
'동결 배아 사용 여부', '신선 배아 사용 여부', '기증 배아 사용 여부', '임신 성공 확률']

In [7]:
df[columns3]

,채취된 신선 난자 수,수정 시도된 난자 수,해동된 배아 수,저장된 배아 수,총 생성 배아 수,이식된 배아 수,미세주입(ICSI) 배아 이식 수,해동 난자 사용 여부,신선 난자 사용 여부,난자 출처,정자 출처,난자 기증자 나이,정자 기증자 나이,동결 배아 사용 여부,신선 배아 사용 여부,기증 배아 사용 여부,임신 성공 확률
0,6-10,6-10,0,0,6-10,2.0,0.0,False,False,본인 제공,배우자 제공,알 수 없음,알 수 없음,False,True,False,0.0
1,0,16-20,0,1-5,6-10,2.0,2.0,True,False,기증 제공,배우자 제공,만26-30세,알 수 없음,False,True,False,0.0
2,1-5,1-5,0,0,1-5,3.0,3.0,False,False,본인 제공,배우자 제공,알 수 없음,알 수 없음,False,True,False,0.0
3,26-30,26-30,0,0,11-15,2.0,0.0,False,False,본인 제공,배우자 제공,알 수 없음,알 수 없음,False,True,False,0.0
4,0,0,6-10,0,0,2.0,0.0,False,False,기증 제공,기증 제공,알 수 없음,알 수 없음,True,False,True,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
126239,16-20,16-20,0,0,6-10,3.0,0.0,False,False,본인 제공,배우자 제공,알 수 없음,알 수 없음,False,True,False,1.0
126240,6-10,6-10,0,1-5,6-10,1.0,0.0,False,False,본인 제공,배우자 제공,알 수 없음,알 수 없음,False,True,False,0.0
126241,11-15,11-15,0,1-5,1-5,1.0,1.0,False,False,본인 제공,배우자 제공,알 수 없음,알 수 없음,False,True,False,1.0
126242,1-5,1-5,0,0,1-5,1.0,1.0,False,False,본인 제공,배우자 제공,알 수 없음,알 수 없음,False,True,False,0.0
126243,0,0,1-5,0,0,1.0,NaN,False,False,본인 제공,기증 제공,알 수 없음,만20세 이하,True,False,False,0.0

In [8]:
for col in columns3:
    print(f"컬럼명: {col}")
    print(f"고유값 목록 ({df[col].nunique()}개): {df[col].unique().tolist()}")
    print("-" * 80)

컬럼명: 채취된 신선 난자 수
고유값 목록 (10개): ['6-10', '0', '1-5', '26-30', '16-20', '21-25', '11-15', '31-35', nan, '>40', '36-40']
--------------------------------------------------------------------------------
컬럼명: 수정 시도된 난자 수
고유값 목록 (10개): ['6-10', '16-20', '1-5', '26-30', '0', '21-25', '11-15', '31-35', nan, '>40', '36-40']
--------------------------------------------------------------------------------
컬럼명: 해동된 배아 수
고유값 목록 (4개): ['0', '6-10', '1-5', '>10']
--------------------------------------------------------------------------------
컬럼명: 저장된 배아 수
고유값 목록 (6개): ['0', '1-5', '6-10', '11-15', '>20', nan, '16-20']
--------------------------------------------------------------------------------
컬럼명: 총 생성 배아 수
고유값 목록 (8개): ['6-10', '1-5', '11-15', '0', '16-20', '21-25', '26-30', nan, '>30']
--------------------------------------------------------------------------------
컬럼명: 이식된 배아 수
고유값 목록 (4개): [2.0, 3.0, 0.0, 1.0, nan]
--------------------------------------------------------------------------------
컬럼명: 미세주입(ICSI) 배아 이식 수
고유값 목록 (4개): [0.0, 2.0, 3.0, 1.0, nan]
--------------------------------------------------------------------------------
컬럼명: 해동 난자 사용 여부
고유값 목록 (2개): [False, True]
--------------------------------------------------------------------------------
컬럼명: 신선 난자 사용 여부
고유값 목록 (2개): [False, True]
--------------------------------------------------------------------------------
컬럼명: 난자 출처
고유값 목록 (3개): ['본인 제공', '기증 제공', '알 수 없음']
--------------------------------------------------------------------------------
컬럼명: 정자 출처
고유값 목록 (5개): ['배우자 제공', '기증 제공', '배우자 및 기증 제공', '미할당', '알 수 없음']
--------------------------------------------------------------------------------
컬럼명: 난자 기증자 나이
고유값 목록 (6개): ['알 수 없음', '만26-30세', '만21-25세', '만31-35세', '만20세 이하', '만36-40세']
--------------------------------------------------------------------------------
컬럼명: 정자 기증자 나이
고유값 목록 (8개): ['알 수 없음', '만21-25세', '만31-35세', '만36-40세', '만26-30세', '만41-45세', '만20세 이하', '>45']
--------------------------------------------------------------------------------
컬럼명: 동결 배아 사용 여부
고유값 목록 (2개): [False, True]
--------------------------------------------------------------------------------
컬럼명: 신선 배아 사용 여부
고유값 목록 (2개): [True, False]
--------------------------------------------------------------------------------
컬럼명: 기증 배아 사용 여부
고유값 목록 (2개): [False, True]
--------------------------------------------------------------------------------
컬럼명: 임신 성공 확률
고유값 목록 (396개): [0.0, 1.0, 0.3333333333333333, 0.5, 0.6, 0.2857142857142857, 0.8, 0.2727272727272727, 0.4, 0.3846153846153846, 0.3, 0.75, 0.2105263157894736, 0.1111111111111111, 0.3529411764705882, 0.2307692307692307, 0.1666666666666666, 0.6666666666666666, 0.2777777777777778, 0.2222222222222222, 0.1428571428571428, 0.25, 0.4285714285714285, 0.3571428571428571, 0.2, 0.1728395061728395, 0.125, 0.0666666666666666, 0.4444444444444444, 0.5555555555555556, 0.2368766404199474, 0.0833333333333333, 0.1333333333333333, 0.4117647058823529, 0.6818181818181818, 0.238095238095238, 0.0192307692307692, 0.4545454545454545, 0.1304347826086956, 0.2272727272727272, 0.2142857142857142, 0.32, 0.1538461538461538, 0.4615384615384615, 0.1, 0.6468120805369127, 0.3157894736842105, 0.5454545454545454, 0.4375, 0.1019108280254777, 0.5714285714285714, 0.391304347826087, 0.1176470588235294, 0.7142857142857142, 0.2987012987012987, 0.0909090909090909, 0.375, 0.3636363636363636, 0.5263157894736842, 0.217391304347826, 0.16, 0.1818181818181818, 0.1875, 0.3076923076923077, 0.6923076923076923, 0.3166666666666666, 0.0384615384615384, 0.2375, 0.3428571428571428, 0.625, 0.3508771929824561, 0.3606612685560054, 0.4429824561403508, 0.2439024390243902, 0.1650485436893204, 0.2941176470588235, 0.6363636363636364, 0.3125, 0.0714285714285714, 0.8333333333333333, 0.1451612903225806, 0.2702702702702703, 0.1052631578947368, 0.8571428571428571, 0.5789473684210527, 0.2647058823529412, 0.2962962962962963, 0.2337662337662337, 0.0869565217391304, 0.45, 0.7666666666666666, 0.7777777777777778, 0.8333333333333334, 0.2692307692307692, 0.4295774647887324, 0.7142857142857143, 0.2352941176470588, 0.2876254180602006, 0.5384615384615384, 0.2666666666666666, 0.2916666666666667, 0.0588235294117647, 0.5294117647058824, 0.2560975609756097, 0.1764705882352941, 0.1904761904761904, 0.05, 0.0967741935483871, 0.064516129032258, 0.367816091954023, 0.2217898832684824, 0.15, 0.0526315789473684, 0.5833333333333334, 0.3478260869565217, 0.3492063492063492, 0.4166666666666666, 0.2580645161290322, 0.3461538461538461, 0.7857142857142857, 0.4641025641025641, 0.3214285714285714, 0.2121212121212121, 0.1794871794871795, 0.2068965517241379, 0.0769230769230769, 0.0285714285714285, 0.0081967213114754, 0.1578947368421052, 0.6153846153846154, 0.475, 0.5238095238095238, 0.2903225806451613, 0.62, 0.0555555555555555, 0.3414634146341463, 0.875, 0.1481481481481481, 0.6764705882352942, 0.1470588235294117, 0.5256410256410255, 0.4666666666666667, 0.5333333333333333, 0.3209876543209876, 0.3188405797101449, 0.2752293577981651, 0.2954545454545454, 0.4166666666666667, 0.325, 0.2631578947368421, 0.2333333333333333, 0.1739130434782608, 0.3566666666666667, 0.3111111111111111, 0.4516129032258064, 0.5833333333333333, 0.4090909090909091, 0.4642857142857142, 0.3043478260869565, 0.4672897196261682, 0.1129032258064516, 0.3939393939393939, 0.2638888888888889, 0.0188679245283018, 0.037037037037037, 0.7, 0.0344827586206896, 0.3409090909090909, 0.2261904761904762, 0.3272727272727272, 0.28, 0.1363636363636363, 0.3888888888888889, 0.4047619047619047, 0.36, 0.1785714285714285, 0.3397435897435897, 0.3611111111111111, 0.55, 0.3782051282051282, 0.1855203619909502, 0.76, 0.3513513513513513, 0.3764705882352941, 0.4666666666666666, 0.4210526315789473, 0.1346153846153846, 0.4482758620689655, 0.0625, 0.3540372670807453, 0.1326530612244898, 0.3372093023255814, 0.3643410852713178, 0.4833333333333333, 0.1923076923076923, 0.4583333333333333, 0.3088803088803089, 0.303030303030303, 0.2926829268292683, 0.2363636363636363, 0.5217391304347826, 0.4761904761904761, 0.0416666666666666, 0.5119047619047619, 0.4137931034482758, 0.06, 0.2321428571428571, 0.7333333333333334, 0.2077922077922078, 0.08, 0.1777777777777777, 0.04, 0.215, 0.1951219512195122, 0.3181818181818182, 0.5045454545454545, 0.7336065573770492, 0.1940298507462686, 0.2894736842105263, 0.3823529411764705, 0.28125, 0.203125, 0.5023809523809524, 0.2875481386392811, 0.3523316062176165, 0.4193548387096774, 0.4428571428571428, 0.352112676056338, 0.2571428571428571, 0.3424947145877378, 0.4155844155844156, 0.2258064516129032, 0.59375, 0.0434782608695652, 0.1621621621621621, 0.5625, 0.6875, 0.21875, 0.3653846153846153, 0.5609756097560976, 0.3809523809523809, 0.1262135922330097, 0.756, 0.1041666666666666, 0.3269230769230768, 0.1944444444444444, 0.4782608695652174, 0.7222222222222222, 0.2096774193548387, 0.3870967741935484, 0.8125, 0.4411764705882353, 0.075, 0.3103448275862069, 0.3666666666666666, 0.0952380952380952, 0.5151515151515151, 0.4824561403508772, 0.24, 0.4705882352941176, 0.1290322580645161, 0.3928571428571428, 0.1298701298701298, 0.3676470588235294, 0.2887323943661972, 0.3815789473684211, 0.2409171075837742, 0.5892857142857142, 0.5520833333333334, 0.7071428571428572, 0.5862068965517241, 0.12, 0.4468085106382978, 0.38, 0.2608695652173913, 0.2473118279569892, 0.043103448275862, 0.2051282051282051, 0.2505376344086021, 0.0294117647058823, 0.4324324324324324, 0.2619047619047619, 0.1929824561403508, 0.48, 0.4736842105263157, 0.3448275862068966, 0.5194805194805194, 0.44, 0.2758620689655172, 0.3888888888888888, 0.4242424242424242, 0.3703703703703703, 0.192, 0.7272727272727273, 0.1518987341772152, 0.18, 0.1573033707865168, 0.6333333333333333, 0.3898305084745763, 0.4878048780487805, 0.3315789473684211, 0.8017241379310345, 0.1829268292682926, 0.4347826086956521, 0.2575757575757575, 0.1724137931034483, 0.046875, 0.2083333333333333, 0.1976744186046511, 0.9166666666666669, 0.2461538461538461, 0.4897959183673469, 0.0238095238095238, 0.2329059829059828, 0.0062111801242236, 0.2492012779552715, 0.3201827242524917, 0.4074074074074074, 0.3984375, 0.2972972972972973, 0.1851851851851851, 0.2569444444444444, 0.1455223880597015, 0.3863636363636363, 0.2833333333333333, 0.631578947368421, 0.202127659574468, 0.4360902255639097, 0.2592592592592592, 0.0059880239520958, 0.1698113207547169, 0.5416666666666666, 0.6379310344827586, 0.6428571428571429, 0.422077922077922, 0.2285714285714285, 0.3684210526315789, 0.4594594594594595, 0.3421052631578947, 0.1521739130434782, 0.2413793103448276, 0.9090909090909092, 0.1463414634146341, 0.3204787234042553, 0.58, 0.525, 0.4871987951807229, 0.0571428571428571, 0.7719298245614036, 0.6845238095238095, 0.1555555555555555, 0.1914893617021276, 0.6212121212121212, 0.6791666666666667, 0.2325581395348837, 0.5230769230769231, 0.4339622641509434, 0.1153846153846153, 0.1071428571428571, 0.449438202247191, 0.6896551724137931, 0.6125, 0.3375, 0.7211538461538461, 0.35, 0.0073529411764705, 0.2463768115942029, 0.7727272727272727, 0.2781065088757396, 0.2956989247311828, 0.4970760233918128, 0.548611111111111, 0.2432432432432432, 0.3004484304932735, 0.2291666666666666, 0.4230769230769231, 0.65, 0.4649532710280373, 0.3398058252427184, 0.1742424242424242, 0.3023255813953488, 0.5222222222222221, 0.3725490196078431, 0.3587786259541984, 0.4150943396226415, 0.7391304347826086, 0.3227383863080684, 0.4125, 0.3910554264852306, 0.1115702479338843, 0.2424242424242424, 0.6134831460674157, 0.6304347826086957, 0.4981617647058823, 0.1891891891891892, 0.5172413793103449]
--------------------------------------------------------------------------------

In [23]:
df[columns3].isnull().sum()

채취된 신선 난자 수            847
수정 시도된 난자 수            847
해동된 배아 수                 0
저장된 배아 수               847
총 생성 배아 수              847
이식된 배아 수               847
미세주입(ICSI) 배아 이식 수    8890
해동 난자 사용 여부              0
신선 난자 사용 여부              0
난자 출처                    0
정자 출처                    0
난자 기증자 나이                0
정자 기증자 나이                0
동결 배아 사용 여부              0
신선 배아 사용 여부              0
기증 배아 사용 여부              0
임신 성공 확률                 0
dtype: int64

In [10]:
# 난자 기증자 나이, 정자 기증자 나이 -> 중앙값 
# 컬럼명: 난자 기증자 나이
#고유값 목록 (6개): ['알 수 없음', '만26-30세', '만21-25세', '만31-35세', '만20세 이하', '만36-40세']
# --------------------------------------------------------------------------------
#컬럼명: 정자 기증자 나이
#고유값 목록 (8개): ['알 수 없음', '만21-25세', '만31-35세', '만36-40세', '만26-30세', '만41-45세', '만20세 이하', '>45']

### 0. 난자 기증자 나이 -> 중앙값

In [8]:
age_mapping = {
    '만20세 이하': 20, '만21-25세': 23, '만26-30세': 28, '만31-35세': 33, '만36-40세': 38,
     '알 수 없음': -1
}
df['난자 기증자 나이'] = df['난자 기증자 나이'].map(age_mapping)

In [12]:
print(df['난자 기증자 나이'].value_counts().sort_index())

난자 기증자 나이
-1     111981
 20       380
 23      2565
 28      4918
 33      6203
 38       197
Name: count, dtype: int64

-  알 수 없음 에 대한 ?

In [12]:
avg = df.groupby('난자 기증자 나이')['임신 성공 확률'].mean()
print(avg.sort_index())

난자 기증자 나이
0     0.256007
20    0.272368
23    0.341125
28    0.359941
33    0.316426
38    0.309645
Name: 임신 성공 확률, dtype: float64

In [ ]:
# 알 수 없음 --- 난자 출처 변수랑 확인

In [13]:
df['난자 출처'].unique().tolist()

['본인 제공', '기증 제공', '알 수 없음']

In [14]:
len (df[df['난자 출처']== '본인 제공' ])

109340

In [17]:
# 1. 문자열 매핑 우선 적용
age_mapping = {
    '만20세 이하': 20,
    '만21-25세': 23,
    '만26-30세': 28,
    '만31-35세': 33,
    '만36-40세': 38
}
# '알 수 없음' 제외하고 먼저 매핑
df['난자 기증자 나이'] = df['난자 기증자 나이'].map(age_mapping)

# 2. '알 수 없음' 조건 처리
con1 = (df['난자 기증자 나이'] == '알 수 없음') & (df['난자 출처'] == '본인 제공')
con2 = (df['난자 기증자 나이'] == '알 수 없음') & (df['난자 출처'] != '본인 제공')

df.loc[con1, '난자 기증자 나이'] = -1  # 본인 난자 - 해당 없음
df.loc[con2, '난자 기증자 나이'] = 0   # 알 수 없음

In [ ]:
# 난자 기증자 나이 -- 알수 없음 -- 타겟값 분포

### 1. 정자 기증자 나이 -> 중앙값

In [9]:
age_mapping_1 = {
    '만20세 이하': 18, '만21-25세': 23, '만26-30세': 28, '만31-35세': 33, '만36-40세': 38,
     '만41-45세': 43, '>45' : 48, '알 수 없음': -1
}
df['정자 기증자 나이'] = df['정자 기증자 나이'].map(age_mapping_1)

In [14]:
print(df['정자 기증자 나이'].value_counts().sort_index())

정자 기증자 나이
-1     104198
 18       890
 23      4748
 28      4390
 33      4216
 38      4472
 43      3217
 48       113
Name: count, dtype: int64

In [12]:
avg = df.groupby('정자 기증자 나이')['임신 성공 확률'].mean()
print(avg.sort_index())

정자 기증자 나이
0     0.260733
18    0.257376
23    0.285780
28    0.284543
33    0.281584
38    0.294632
43    0.282685
48    0.206490
Name: 임신 성공 확률, dtype: float64

- 알 수 없음은 -- -정자 출처 확인

## 3.  왜 '>n' 그냥 앞 구간에 포함시켰는지에 대한 논리적 설명

In [9]:
import numpy as np

# 1. 대상 칼럼 리스트
range_columns = [
    '채취된 신선 난자 수',
    '수정 시도된 난자 수',
    '해동된 배아 수',
    '저장된 배아 수',
    '총 생성 배아 수'
]

# 2. 변환 함수 정의
def extract_max(val):
    if pd.isna(val):
        return -1  # 결측치도 -1 처리
    if isinstance(val, str):
        if '-' in val:
            try:
                return int(val.split('-')[1])     # 예: '1-5' → 5
            except:
                return -1
        elif val.startswith('>'):
            try:
                return int(val[1:]) +5              # 예: '>40' → 40
            except:
                return -1
        elif val.isdigit():
            return int(val)                       # 예: '0' → 0
    return -1  # 기타 예외 처리


# 3. 각 컬럼에 적용
for col in range_columns:
    df[col] = df[col].apply(extract_max)

In [10]:
for col in range_columns:
    print(f"📌 {col}")
    print(df[col].value_counts().sort_index())
    print("-" * 60)

📌 채취된 신선 난자 수
채취된 신선 난자 수
-1       847
 0     39876
 5     15916
 10    23820
 15    20664
 20    13349
 25     6810
 30     2948
 35     1243
 40      484
 45      287
Name: count, dtype: int64
------------------------------------------------------------
📌 수정 시도된 난자 수
수정 시도된 난자 수
-1       847
 0     29065
 5     24318
 10    32108
 15    21094
 20    10864
 25     4895
 30     1893
 35      743
 40      272
 45      145
Name: count, dtype: int64
------------------------------------------------------------
📌 해동된 배아 수
해동된 배아 수
0     98616
5     24100
10     2947
15      581
Name: count, dtype: int64
------------------------------------------------------------
📌 저장된 배아 수
저장된 배아 수
-1       847
 0     83335
 5     32993
 10     6725
 15     1528
 20      507
 25      309
Name: count, dtype: int64
------------------------------------------------------------
📌 총 생성 배아 수
총 생성 배아 수
-1       847
 0     32062
 5     42973
 10    30852
 15    13256
 20     4498
 25     1319
 30      327
 35      110
Name: count, dtype: int64
------------------------------------------------------------

In [11]:
for col in range_columns:
    print(f"📌 {col} ")
    print(df.groupby(col)['임신 성공 확률'].mean())
    print("-" * 60)

📌 채취된 신선 난자 수
채취된 신선 난자 수
-1     0.124224
 0     0.265225
 5     0.155706
 10    0.254088
 15    0.310770
 20    0.334407
 25    0.328686
 30    0.255759
 35    0.201050
 40    0.144628
 45    0.106272
Name: 임신 성공 확률, dtype: float64
------------------------------------------------------------
📌 수정 시도된 난자 수
수정 시도된 난자 수
-1     0.124224
 0     0.227525
 5     0.185144
 10    0.291153
 15    0.327865
 20    0.343179
 25    0.317614
 30    0.249242
 35    0.189996
 40    0.158088
 45    0.113793
Name: 임신 성공 확률, dtype: float64
------------------------------------------------------------
📌 해동된 배아 수
해동된 배아 수
0     0.271075
5     0.238431
10    0.267030
15    0.301111
Name: 임신 성공 확률, dtype: float64
------------------------------------------------------------
📌 저장된 배아 수
저장된 배아 수
-1     0.124224
 0     0.224564
 5     0.363614
 10    0.343271
 15    0.184173
 20    0.056213
 25    0.019417
Name: 임신 성공 확률, dtype: float64
------------------------------------------------------------
📌 총 생성 배아 수
총 생성 배아 수
-1     0.124224
 0     0.206813
 5     0.230560
 10    0.329118
 15    0.351564
 20    0.341891
 25    0.261195
 30    0.244139
 35    0.181818
Name: 임신 성공 확률, dtype: float64
------------------------------------------------------------

In [ ]:
- 합쳐줬다. 확률 감소하는 거 확인 - 해동된 배아 수만 15에서 튐 
-

In [27]:
avg_success = df.groupby('정자 기증자 나이')['임신 성공 확률'].mean()
# 2. 평균 확률이 가장 높은 나이 찾기
best_age = avg_success.idxmax()

best_age

38

In [28]:

# 3. 절댓값 차이로 파생변수 생성
df['정자_나이차'] = (df['정자 기증자 나이'] - best_age).abs()

In [29]:
df.head()

,ID,환자 시술 당시 나이,시술 유형,세부 시술 유형,배란 자극 시술 여부,단일 배아 이식 여부,불임 원인 - 난관 질환,불임 원인 - 배란 장애,불임 원인 - 남성 요인,불임 원인 - 자궁내막증,...,난자 기증자 나이,정자 기증자 나이,동결 배아 사용 여부,신선 배아 사용 여부,기증 배아 사용 여부,착상 전 PGD 시행 여부,착상 전 PGS 시행 여부,배아 이식 후 경과일,임신 성공 확률,정자_나이차
0,TRAIN_000000,만18-34세,IVF,IVF,True,False,False,True,False,False,...,-1,-1,False,True,False,False,False,5.0,0.0,39
1,TRAIN_000001,만45-50세,IVF,ICSI,False,False,False,False,False,False,...,28,-1,False,True,False,False,False,3.0,0.0,39
2,TRAIN_000002,만43-44세,IVF,ICSI,True,False,False,False,False,False,...,-1,-1,False,True,False,False,False,2.0,0.0,39
3,TRAIN_000003,만35-37세,IVF,IVF,True,False,False,False,False,False,...,-1,-1,False,True,False,False,False,3.0,0.0,39
4,TRAIN_000004,만40-42세,IVF,Unknown,False,False,False,True,False,False,...,-1,-1,True,False,True,False,False,2.0,1.0,39

In [31]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 126244 entries, 0 to 126243
Data columns (total 36 columns):
 #   Column              Non-Null Count   Dtype
---  ------              --------------   -----
 0   ID                  126244 non-null  object
 1   환자 시술 당시 나이         126244 non-null  object
 2   시술 유형               126244 non-null  object
 3   세부 시술 유형            126242 non-null  object
 4   배란 자극 시술 여부         126244 non-null  bool
 5   단일 배아 이식 여부         126244 non-null  bool
 6   불임 원인 - 난관 질환       126244 non-null  bool
 7   불임 원인 - 배란 장애       126244 non-null  bool
 8   불임 원인 - 남성 요인       126244 non-null  bool
 9   불임 원인 - 자궁내막증       126244 non-null  bool
 10  불임 원인 - 불명확         126244 non-null  bool
 11  이전 IVF 시술 횟수        126244 non-null  object
 12  이전 DI 시술 횟수         126244 non-null  object
 13  이전 총 임신 횟수          114541 non-null  object
 14  이전 총 임신 성공 횟수       121163 non-null  object
 15  총 생성 배아 수           125397 non-null  object
 16  이식된 배아 수            125397 non-null  float64
 17  미세주입(ICSI) 배아 이식 수  117354 non-null  float64
 18  저장된 배아 수            125397 non-null  object
 19  해동된 배아 수            126244 non-null  object
 20  해동 난자 사용 여부         126244 non-null  bool
 21  채취된 신선 난자 수         125397 non-null  object
 22  신선 난자 사용 여부         126244 non-null  bool
 23  수정 시도된 난자 수         125397 non-null  object
 24  난자 출처               126244 non-null  object
 25  정자 출처               126244 non-null  object
 26  난자 기증자 나이           126244 non-null  int64
 27  정자 기증자 나이           0 non-null       float64
 28  동결 배아 사용 여부         126244 non-null  bool
 29  신선 배아 사용 여부         126244 non-null  bool
 30  기증 배아 사용 여부         126244 non-null  bool
 31  착상 전 PGD 시행 여부      126244 non-null  bool
 32  착상 전 PGS 시행 여부      126244 non-null  bool
 33  배아 이식 후 경과일         108804 non-null  float64
 34  임신 성공 확률            126244 non-null  float64
 35  정자_나이차              126244 non-null  int64
dtypes: bool(14), float64(5), int64(2), object(15)
memory usage: 22.9+ MB

In [ ]:
# 정자_나이차 생성: -1이면 -1, 아니면 |정자 나이 - 38|
df['정자_나이차'] = df['정자 기증자 나이'].apply(lambda x: -1 if x == -1 else abs(x - 38))

# 난자_나이차 생성: -1이면 -1, 아니면 |난자 나이 - 28|
df['난자_나이차'] = df['난자 기증자 나이'].apply(lambda x: -1 if x == -1 else abs(x - 28))

In [10]:
# 정자 기증자 나이별 임신 성공 확률 평균 계산
avg = df.groupby('정자 기증자 나이')['임신 성공 확률'].mean()

# 성공 확률이 가장 높은 나이 찾기 (단, 나이가 -1이 아닌 경우에 한해)
max_age = avg[avg.index != -1].idxmax()

# 파생변수 생성
def calc_age_distance(age):
    if age == -1:
        return -1
    else:
        return abs(age - max_age)

df['정자 나이차'] = df['정자 기증자 나이'].apply(calc_age_distance)

In [11]:
df.head()

,ID,환자 시술 당시 나이,시술 유형,세부 시술 유형,배란 자극 시술 여부,단일 배아 이식 여부,불임 원인 - 난관 질환,불임 원인 - 배란 장애,불임 원인 - 남성 요인,불임 원인 - 자궁내막증,...,난자 기증자 나이,정자 기증자 나이,동결 배아 사용 여부,신선 배아 사용 여부,기증 배아 사용 여부,착상 전 PGD 시행 여부,착상 전 PGS 시행 여부,배아 이식 후 경과일,임신 성공 확률,정자 나이차
0,TRAIN_000000,만18-34세,IVF,IVF,True,False,False,True,False,False,...,-1,-1,False,True,False,False,False,5.0,0.0,-1
1,TRAIN_000001,만45-50세,IVF,ICSI,False,False,False,False,False,False,...,28,-1,False,True,False,False,False,3.0,0.0,-1
2,TRAIN_000002,만43-44세,IVF,ICSI,True,False,False,False,False,False,...,-1,-1,False,True,False,False,False,2.0,0.0,-1
3,TRAIN_000003,만35-37세,IVF,IVF,True,False,False,False,False,False,...,-1,-1,False,True,False,False,False,3.0,0.0,-1
4,TRAIN_000004,만40-42세,IVF,Unknown,False,False,False,True,False,False,...,-1,-1,True,False,True,False,False,2.0,1.0,-1